/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateFolderTaskArgs } from "./CreateFolderTaskArgs";
import { UpdateFolderTaskArgs } from "./UpdateFolderTaskArgs";
import { DeleteFolderTaskArgs } from "./DeleteFolderTaskArgs";
import { FolderTaskFindManyArgs } from "./FolderTaskFindManyArgs";
import { FolderTaskFindUniqueArgs } from "./FolderTaskFindUniqueArgs";
import { FolderTask } from "./FolderTask";
import { FolderFindManyArgs } from "../../folder/base/FolderFindManyArgs";
import { Folder } from "../../folder/base/Folder";
import { TaskFindManyArgs } from "../../task/base/TaskFindManyArgs";
import { Task } from "../../task/base/Task";
import { FolderTaskService } from "../folderTask.service";

@graphql.Resolver(() => FolderTask)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FolderTaskResolverBase {
  constructor(
    protected readonly service: FolderTaskService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "read",
    possession: "any",
  })
  async _folderTasksMeta(
    @graphql.Args() args: FolderTaskFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [FolderTask])
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "read",
    possession: "any",
  })
  async folderTasks(
    @graphql.Args() args: FolderTaskFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FolderTask[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "FolderTask",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => FolderTask, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "read",
    possession: "own",
  })
  async folderTask(
    @graphql.Args() args: FolderTaskFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FolderTask | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "FolderTask",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => FolderTask)
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "create",
    possession: "any",
  })
  async createFolderTask(
    @graphql.Args() args: CreateFolderTaskArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FolderTask> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "FolderTask",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FolderTask"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => FolderTask)
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "update",
    possession: "any",
  })
  async updateFolderTask(
    @graphql.Args() args: UpdateFolderTaskArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FolderTask | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "FolderTask",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FolderTask"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FolderTask)
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "delete",
    possession: "any",
  })
  async deleteFolderTask(
    @graphql.Args() args: DeleteFolderTaskArgs
  ): Promise<FolderTask | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Folder])
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "read",
    possession: "any",
  })
  async folderId(
    @graphql.Parent() parent: FolderTask,
    @graphql.Args() args: FolderFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Folder[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Folder",
    });
    const results = await this.service.findFolderId(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Task])
  @nestAccessControl.UseRoles({
    resource: "FolderTask",
    action: "read",
    possession: "any",
  })
  async taskId(
    @graphql.Parent() parent: FolderTask,
    @graphql.Args() args: TaskFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Task[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Task",
    });
    const results = await this.service.findTaskId(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
