version: '3.2'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres-db
    restart: unless-stopped
    user: postgres
    networks:
      rede-psql:
        ipv4_address: 10.0.0.20
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    links:
      - pgadmin

  postgres-setup:
    image: postgres:alpine
    container_name: postres-setup
    networks:
      rede-psql:
        ipv4_address: 10.0.0.12
    depends_on:
      - postgres
    volumes:
      - .:/app
    entrypoint: [ "sh" ]
    command:
      [
        "-c",
        "sleep 5 && psql 'postgresql://postgres:postgres@10.0.0.20:5432' < /app/createDB.sql"
      ]

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-pgadmin
    restart: unless-stopped
    networks:
      rede-psql:
        ipv4_address: 10.0.0.11
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres

networks:
  rede-psql:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.1/24

volumes:
  data:
